version: '3'

volumes:
  pg_data:
  # Изменим имена volume'ов для ясности
  static_backend_volume:
  media_backend_volume:
  static_frontend_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    # Команда для сбора статики перед запуском Gunicorn
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn kittygram_backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_backend_volume:/app/static  # Сопоставляем с STATIC_ROOT
      - media_backend_volume:/app/media   # Сопоставляем с MEDIA_ROOT

  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /static_frontend/ # Копируем в новую папку
    volumes:
      - static_frontend_volume:/static_frontend

  gateway:
    build: ./nginx/
    ports:
      - 8000:80
    volumes:
      # Nginx должен иметь доступ ко всем трем папкам
      - static_frontend_volume:/static_frontend:ro
      - static_backend_volume:/static_backend:ro
      - media_backend_volume:/media_backend:ro
    depends_on: # Явно указываем зависимости
      - backend
      - frontend