server {
    listen 80;
    server_name localhost; # Добавим для ясности

    # Прямой путь к API бэкенда
    location /api/ {
        proxy_set_header Host $http_host;
        proxy_pass http://backend:8000/api/;
    }

    # Прямой путь к админке Django
    location /admin/ {
        proxy_set_header Host $http_host;
        proxy_pass http://backend:8000/admin/;
    }

    # Раздача медиафайлов, загруженных пользователями
    location /media/ {
        alias /media_backend/;
    }

    # Раздача статики Django (для стилей админки)
    # Важно, чтобы этот путь отличался от статики фронтенда
    location /static_django/ {
        alias /static_backend/;
    }

    # Раздача фронтенда (SPA). Этот блок должен быть последним.
    # Он обрабатывает все остальные запросы.
    location / {
        # `root` указывает на папку, где лежит сборка фронтенда.
        root /static_frontend;
        # Сначала ищем файл, потом папку, если не нашли - отдаем index.html
        # Это стандартный паттерн для работы роутинга в SPA.
        try_files $uri /index.html;
    }
}
